#! /bin/bash

bun build --compile --minify --sourcemap ./src/index.ts --compile --outfile dist/leb-cli-darwin-arm64
bun build --compile --minify --sourcemap --target=bun-linux-x64-modern ./src/index.ts --outfile dist/leb-cli-linux-x64
bun build --compile --minify --sourcemap --target=bun-linux-arm64 ./src/index.ts --outfile dist/leb-cli-linux-arm64
bun build --compile --minify --sourcemap --target=bun-windows-x64-modern ./src/index.ts --outfile dist/leb-cli-windows-x64
